# Generated by Django 3.2.2 on 2021-07-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='class_in_school',
            field=models.CharField(choices=[('JSS1', 'Junior1'), ('JSS2', 'Junior2'), ('JSS3', 'Junior3'), ('SS1', 'Senior1'), ('SS2', 'Senior2'), ('SS3', 'Senior3')], max_length=20),
        ),
    ]
