# Generated by Django 3.2.2 on 2021-07-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210708_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='parent_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
