# Generated by Django 3.2.2 on 2021-07-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210708_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
