# Generated by Django 3.2.2 on 2021-07-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210708_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('SCIENCE', 'Science'), ('ART', 'Art'), ('COMMERCIAL', 'Commercial'), ('None', 'None')], max_length=20),
        ),
    ]
